Parameters:
  LatestAMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64

  InstanceType:
    Type: String
    Default: m5.large

  SecretName:
    Type: String
    Default: vscode-password
    Description: The name of the secrets manager secret that stores the password to be used for the VSCode Server. The password must be a simple plaintext string with no JSON.

Mappings:
  Prefixes:
    ap-northeast-1:
      PrefixList: pl-58a04531
    ap-northeast-2:
      PrefixList: pl-22a6434b
    ap-south-1:
      PrefixList: pl-9aa247f3
    ap-southeast-1:
      PrefixList: pl-31a34658
    ap-southeast-2:
      PrefixList: pl-b8a742d1
    ca-central-1:
      PrefixList: pl-38a64351
    eu-central-1:
      PrefixList: pl-a3a144ca
    eu-north-1:
      PrefixList: pl-fab65393
    eu-west-1:
      PrefixList: pl-4fa04526
    eu-west-2:
      PrefixList: pl-93a247fa
    eu-west-3:
      PrefixList: pl-75b1541c
    sa-east-1:
      PrefixList: pl-5da64334
    us-east-1:
      PrefixList: pl-3b927c52
    us-east-2:
      PrefixList: pl-b6a144df
    us-west-1:
      PrefixList: pl-4ea04527
    us-west-2:
      PrefixList: pl-82a045eb

Resources:
  Network:
    Type: !Rain::Module ../../RainModules/vpc.yml
    Properties:
      Name: gitlab-server

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: gitlab-server-isg
      SecurityGroupIngress:
        - Description: Allow HTTP from com.amazonaws.global.cloudfront.origin-facing
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourcePrefixListId: !FindInMap
            - Prefixes
            - !Ref AWS::Region
            - PrefixList
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      Tags:
        - Key: Name
          Value: gitlab-server-isg
      VpcId: !Ref NetworkVPC

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
        Version: "2012-10-17"
      Tags:
        - Key: Name
          Value: gitlab-server-instance

  InstanceRolePolicy:
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - ec2messages:*
              - ssm:UpdateInstanceInformation
              - ssmmessages:*
              - secretsmanager:GetSecretValue
            Effect: Allow
            Resource: '*'
        Version: "2012-10-17"
      PolicyName: InstanceRolePolicy
      RoleName: !Ref InstanceRole

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref InstanceRole

  GitLabServer:
    Type: AWS::EC2::Instance
    DependsOn:
      - InstanceRolePolicy
      - InstanceRole
    CreationPolicy:
      ResourceSignal:
        Timeout: PT30M
    Properties:
      AvailabilityZone: !Select
        - 0
        - !GetAZs
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 128
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !Ref LatestAMI
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - !GetAtt InstanceSecurityGroup.GroupId
      SubnetId: !GetAtt NetworkPublicSubnet1.SubnetId
      Tags:
        - Key: Name
          Value: gitlab-server
      UserData: !Base64
        Fn::Sub: !Rain::Embed GitLabServer.sh

  VSCodeServer:
    Type: AWS::EC2::Instance
    DependsOn:
      - InstanceRolePolicy
      - InstanceRole
    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M
    Properties:
      AvailabilityZone: !Select
        - 0
        - !GetAZs
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 128
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !Ref LatestAMI
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - !GetAtt InstanceSecurityGroup.GroupId
      SubnetId: !GetAtt NetworkPublicSubnet1.SubnetId
      Tags:
        - Key: Name
          Value: vscode-server
      UserData: !Base64
        Fn::Sub: !Rain::Embed VSCodeServer.sh

  GitLabCloudFront:
    Type: !Rain::Module ../../RainModules/cloudfront-nocache.yml
    Properties:
      Name: gitlab-server
      DomainName: !GetAtt GitLabServer.PublicDnsName
      Port: 80
    Overrides:
      Distribution:
        DependsOn: GitLabServer

  VSCodeCloudFront:
    Type: !Rain::Module ../../RainModules/cloudfront-nocache.yml
    Properties:
      Name: vscode-server
      DomainName: !GetAtt VSCodeServer.PublicDnsName
      Port: 8080
    Overrides:
      Distribution: DependsOn:VSCodeServer

Outputs:
  VSCodeURL:
    Value: !Sub https://${VSCodeCloudFrontDistribution.DomainName}/?folder=/home/ec2-user

  GitLabURL:
    Value: !Sub https://${GitLabCloudFrontDistribution.DomainName}/?folder=/home/ec2-user
